# Generated by Django 5.0.7 on 2024-09-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedoctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-10 19:20:21'),
            preserve_default=False,
        ),
    ]
