# Generated by Django 5.0.7 on 2024-09-02 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(blank=True, max_length=200, null=True, verbose_name='تخصص')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام پزشک')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('referral_time', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نوبت بیماران')),
                ('medical_degree_picture', models.ImageField(blank=True, null=True, upload_to='medical_degree_picture/')),
                ('activate_account_doctor', models.BooleanField(default=False, verbose_name='فعال/غیر فعال شدن اکانت دکتر ها')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image_doctor/')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه')),
                ('bio', models.TextField(blank=True, null=True)),
                ('price_doctor', models.CharField(blank=True, max_length=200, null=True, verbose_name='هزینه ویزیت')),
                ('address_doctor', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس مطب دکتر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('SA', 'شنبه'), ('SU', 'یکشنبه'), ('MO', 'دوشنبه'), ('TU', 'سه شنبه'), ('WE', 'چهارشنبه'), ('TH', 'پنج شنبه')], max_length=10, verbose_name='روز هفته')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctor_module.doctors')),
            ],
        ),
    ]
