# Generated by Django 5.0.7 on 2024-08-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
    ]
