# Generated by Django 5.0.7 on 2024-08-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_service_alter_aboutme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images/services', verbose_name='تصویر مقاله'),
        ),
    ]
