# Generated by Django 5.0.7 on 2024-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_read',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='تایم خوانش'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='email',
            field=models.EmailField(default=123123134324, max_length=100, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
