# Generated by Django 5.0.7 on 2024-08-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_article_time_read_articlecomment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='user',
        ),
    ]
