# Generated by Django 5.0.7 on 2024-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_remove_articlecomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='name',
            field=models.CharField(default=131231233213, max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
