# Generated by Django 5.0.7 on 2024-08-22 21:54

import account_module.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=130, null=True, verbose_name='یوزر نیم')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='ایمیل')),
                ('doctor_email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='ایمیل پزشکان')),
                ('email_code_doctor', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='کد ارسالی ایمیل')),
                ('email_code', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='کد ارسالی ایمیل')),
                ('password', models.CharField(max_length=255, verbose_name='پسورد')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('gender', models.CharField(blank=True, choices=[('-', '-'), ('مرد', 'مرد'), ('زن', 'زن')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_completion', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_time_patient', models.DateTimeField(null=True, verbose_name='تاریخ نوبت بیمار')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه')),
                ('phone_number_sms', models.CharField(blank=True, max_length=11, null=True, verbose_name='کد ارسالی تلفن همراه')),
                ('last_login_request', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اکانت ساخته شده')),
                ('is_staff', models.BooleanField(default=False, help_text='Is the user allowed to have access to the admin', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Is the user account currently active', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group', verbose_name='گروه\u200cها')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_user_permissions', to='auth.permission', verbose_name='دسترسی\u200cها')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', account_module.managers.UserManager()),
            ],
        ),
    ]
